# Generated by Django 5.2.13 on 2026-04-14 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerBehaviorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_claims_per_week_3m', models.FloatField(default=0.0)),
                ('avg_claims_per_week_6m', models.FloatField(default=0.0)),
                ('max_claims_in_any_week', models.IntegerField(default=0)),
                ('weeks_since_last_claim', models.IntegerField(default=99)),
                ('avg_approved_amount', models.FloatField(default=0.0)),
                ('std_approved_amount', models.FloatField(default=0.0)),
                ('max_approved_amount', models.FloatField(default=0.0)),
                ('amount_volatility', models.FloatField(default=0.0)),
                ('typical_claim_hours', models.JSONField(default=list)),
                ('claims_on_weekends_ratio', models.FloatField(default=0.0)),
                ('claims_in_monsoon_ratio', models.FloatField(default=0.0)),
                ('avg_zone_match_score', models.FloatField(default=0.8)),
                ('location_consistency', models.FloatField(default=1.0)),
                ('trigger_type_distribution', models.JSONField(default=dict)),
                ('claims_per_trigger_type', models.JSONField(default=dict)),
                ('has_prior_fraud_flag', models.BooleanField(default=False)),
                ('prior_rejected_claims_count', models.IntegerField(default=0)),
                ('appeal_success_rate', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('total_claims_analyzed', models.IntegerField(default=0)),
                ('profile_confidence', models.FloatField(default=0.0)),
                ('worker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
