# Generated by Django 6.0.3 on 2026-03-16 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('policies', '0001_initial'),
        ('triggers', '0001_initial'),
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_lost_hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('payout_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('claim_status', models.CharField(choices=[('created', 'Created'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('review', 'Review')], default='created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='policies.policy')),
                ('trigger_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='triggers.triggerevent')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='workers.workerprofile')),
            ],
            options={
                'unique_together': {('worker', 'policy', 'trigger_event')},
            },
        ),
    ]
