# Generated by Django 6.0.3 on 2026-03-16 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TriggerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(choices=[('heavy_rain', 'Heavy Rain'), ('flood_alert', 'Flood Alert'), ('extreme_heat', 'Extreme Heat'), ('severe_aqi', 'Severe AQI'), ('zone_closure', 'Zone Closure')], max_length=30)),
                ('city', models.CharField(max_length=80)),
                ('zone', models.CharField(max_length=120)),
                ('source_type', models.CharField(default='mock', max_length=50)),
                ('source_value', models.JSONField(default=dict)),
                ('threshold_value', models.JSONField(default=dict)),
                ('event_start', models.DateTimeField()),
                ('event_end', models.DateTimeField()),
                ('severity', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZoneRiskScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=80)),
                ('zone', models.CharField(max_length=120)),
                ('rain_risk_score', models.FloatField(default=0.0)),
                ('heat_risk_score', models.FloatField(default=0.0)),
                ('aqi_risk_score', models.FloatField(default=0.0)),
                ('flood_risk_score', models.FloatField(default=0.0)),
                ('closure_risk_score', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('city', 'zone')},
            },
        ),
    ]
