# Generated by Django 6.0.3 on 2026-03-19 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triggers', '0001_initial'),
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrowdsourcedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(choices=[('heavy_rain', 'Heavy Rain'), ('flood_alert', 'Flood Alert'), ('extreme_heat', 'Extreme Heat'), ('severe_aqi', 'Severe AQI'), ('zone_closure', 'Zone Closure')], max_length=30)),
                ('city', models.CharField(max_length=80)),
                ('zone', models.CharField(max_length=120)),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=15)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('trigger_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_reports', to='triggers.triggerevent')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='workers.workerprofile')),
            ],
        ),
    ]
