# Generated by Django 5.2.13 on 2026-04-14 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='registered_lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='registered_lon',
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name='GridCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('cell_id', models.CharField(max_length=20)),
                ('lat_min', models.FloatField()),
                ('lat_max', models.FloatField()),
                ('lon_min', models.FloatField()),
                ('lon_max', models.FloatField()),
                ('center_lat', models.FloatField()),
                ('center_lon', models.FloatField()),
                ('flood_incidents_12m', models.IntegerField(default=0)),
                ('waterlog_score', models.FloatField(default=0.0)),
                ('elevation_meters', models.FloatField(default=10.0)),
                ('drainage_quality', models.CharField(choices=[('POOR', 'POOR'), ('AVERAGE', 'AVERAGE'), ('GOOD', 'GOOD')], default='AVERAGE', max_length=20)),
                ('avg_aqi_30d', models.FloatField(default=100.0)),
                ('heat_island_factor', models.FloatField(default=1.0)),
                ('historical_disruption_rate', models.FloatField(default=0.1)),
            ],
            options={
                'unique_together': {('city', 'zone', 'cell_id')},
            },
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='grid_cell',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.gridcell'),
        ),
    ]
