# Generated by Django 5.2.13 on 2026-04-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_workerprofile_registered_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='aadhaar_last4',
            field=models.CharField(blank=True, default='', help_text='Last 4 digits of Aadhaar for KYC simulation', max_length=4),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Verified gig worker'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='platform_worker_id',
            field=models.CharField(blank=True, default='', help_text='Delivery partner ID from Swiggy/Zomato/Amazon etc.', max_length=50),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='verification_method',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
