# Generated by Django 5.2.13 on 2026-04-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_add_verification_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='platform',
            field=models.CharField(choices=[('ZOMATO', 'Zomato'), ('SWIGGY', 'Swiggy'), ('AMAZON_FLEX', 'Amazon Flex'), ('BLINKIT', 'Blinkit'), ('FLIPKART', 'Flipkart'), ('DUNZO', 'Dunzo'), ('PORTER', 'Porter'), ('ZEPTO', 'Zepto'), ('BIGBASKET', 'BigBasket'), ('SHADOWFAX', 'Shadowfax'), ('ECOM_EXPRESS', 'Ecom Express'), ('DELHIVERY', 'Delhivery')], default='SWIGGY', max_length=20),
        ),
    ]
