# Generated by Django 5.2.12 on 2026-04-03 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('approved_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fraud_score', models.FloatField(default=0)),
                ('fraud_flags', models.JSONField(blank=True, default=list)),
                ('fraud_model_version', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('MANUAL_REVIEW', 'Manual Review')], default='PENDING', max_length=16)),
                ('auto_processed', models.BooleanField(default=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('payout_ref', models.CharField(blank=True, max_length=50, null=True)),
                ('exclusion_check_passed', models.BooleanField(default=True)),
                ('exclusion_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('exclusion_id', models.CharField(blank=True, max_length=20, null=True)),
                ('appeal_allowed', models.BooleanField(default=True)),
                ('appeal_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('appeal_resolution', models.CharField(blank=True, max_length=255, null=True)),
                ('payout_calculation', models.JSONField(blank=True, default=dict)),
                ('related_trigger_ids', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FraudLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(choices=[('GPS', 'GPS'), ('BEHAVIORAL', 'Behavioral'), ('TEMPORAL', 'Temporal'), ('DUPLICATE', 'Duplicate'), ('CLUSTER', 'Cluster'), ('EARNINGS_INFLATION', 'Earnings Inflation')], max_length=30)),
                ('result', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('WARNING', 'Warning')], max_length=10)),
                ('confidence', models.FloatField(default=0.5)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('model_version', models.CharField(blank=True, default='', max_length=20)),
            ],
        ),
    ]
