# Generated by Django 5.2.12 on 2026-04-03 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('claims', '0001_initial'),
        ('policies', '0001_initial'),
        ('triggers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='policies.weeklypolicy'),
        ),
        migrations.AddField(
            model_name='claim',
            name='trigger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='triggers.disruptiontrigger'),
        ),
    ]
