# Generated by Django 5.2.12 on 2026-04-03 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('UPI', 'UPI'), ('WALLET', 'Wallet'), ('BANK', 'Bank')], default='UPI', max_length=10)),
                ('upi_id', models.CharField(max_length=50)),
                ('transaction_ref', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='INITIATED', max_length=12)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('receipt_url', models.CharField(blank=True, default='', max_length=500)),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payout', to='claims.claim')),
            ],
        ),
    ]
