# Generated by Django 6.0.3 on 2026-03-16 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=80)),
                ('city', models.CharField(max_length=80)),
                ('primary_zone', models.CharField(max_length=120)),
                ('secondary_zone', models.CharField(blank=True, default='', max_length=120)),
                ('avg_weekly_income', models.PositiveIntegerField()),
                ('avg_weekly_hours', models.PositiveIntegerField()),
                ('preferred_work_start', models.TimeField()),
                ('preferred_work_end', models.TimeField()),
                ('payout_method', models.CharField(default='UPI', max_length=80)),
                ('device_id', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('zone', models.CharField(max_length=120)),
                ('status_active', models.BooleanField(default=True)),
                ('order_count', models.PositiveIntegerField(default=0)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='workers.workerprofile')),
            ],
        ),
    ]
