# Generated by Django 5.2.12 on 2026-04-03 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('monitoring_active', models.BooleanField(default=True)),
                ('default_zone', models.CharField(blank=True, default='', help_text='Fallback zone label for city-wide triggers', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'cities',
            },
        ),
        migrations.CreateModel(
            name='DisruptionTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(choices=[('RAIN', 'Rain'), ('HEAT', 'Heat'), ('AQI', 'AQI'), ('FLOOD', 'Flood'), ('ZONE_CLOSURE', 'Zone Closure'), ('CURFEW', 'Curfew')], max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('zone', models.CharField(max_length=100)),
                ('severity', models.IntegerField(default=1)),
                ('threshold_value', models.FloatField(default=0)),
                ('actual_value', models.FloatField(default=0)),
                ('triggered_at', models.DateTimeField()),
                ('duration_hours', models.FloatField(default=1)),
                ('source', models.CharField(default='open_meteo', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('affected_workers_count', models.IntegerField(default=0)),
                ('total_payout_triggered', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_excluded_event', models.BooleanField(default=False)),
                ('exclusion_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('announcement_at', models.DateTimeField(blank=True, help_text='For EX-06: before policy purchase if announced early', null=True)),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='GovernmentAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('alert_type', models.CharField(choices=[('EPIDEMIC', 'Epidemic'), ('LOCKDOWN', 'Lockdown'), ('DISASTER_ACT', 'Disaster Act')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('declared_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='MunicipalAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('zone', models.CharField(blank=True, default='', max_length=100)),
                ('alert_type', models.CharField(default='FLOOD', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('severity', models.IntegerField(default=2)),
            ],
        ),
    ]
