# Generated by Django 5.2.13 on 2026-04-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triggers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disruptiontrigger',
            name='affected_cell_ids',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='disruptiontrigger',
            name='affected_lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='disruptiontrigger',
            name='affected_lon',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='disruptiontrigger',
            name='radius_km',
            field=models.FloatField(default=5.0),
        ),
    ]
