# Generated by Django 5.2.13 on 2026-04-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triggers', '0002_disruptiontrigger_affected_cell_ids_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disruptiontrigger',
            name='trigger_type',
            field=models.CharField(choices=[('ALL', 'All'), ('RAIN', 'Rain'), ('HEAT', 'Heat'), ('AQI', 'AQI'), ('FLOOD', 'Flood'), ('ZONE_CLOSURE', 'Zone Closure'), ('CURFEW', 'Curfew')], max_length=20),
        ),
    ]
