# Generated by Django 6.0.3 on 2026-03-16 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverage_tier', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('plus', 'Plus')], max_length=20)),
                ('weekly_premium', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_covered_hours', models.PositiveIntegerField()),
                ('coverage_ratio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('active_from', models.DateTimeField()),
                ('active_to', models.DateTimeField()),
                ('policy_status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='workers.workerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PremiumHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('premium_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('risk_score', models.FloatField()),
                ('pricing_factors_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_history', to='workers.workerprofile')),
            ],
        ),
    ]
