# Generated by Django 5.2.12 on 2026-04-03 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActuarialReserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(unique=True)),
                ('total_premiums_collected', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_claims_paid', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_claims_pending', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('loss_ratio', models.FloatField(default=0)),
                ('expense_ratio', models.FloatField(default=0.2)),
                ('combined_ratio', models.FloatField(default=0)),
                ('reserve_held', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('solvency_margin', models.FloatField(default=0)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-week_start'],
            },
        ),
        migrations.CreateModel(
            name='ExclusionAcknowledgment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exclusions_version', models.CharField(default='v1.0', max_length=10)),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_fingerprint', models.CharField(blank=True, default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('premium_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coverage_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tier', models.CharField(choices=[('BASIC', 'Basic'), ('STANDARD', 'Standard'), ('PREMIUM', 'Premium')], max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=12)),
                ('exclusions_acknowledged', models.BooleanField(default=False)),
                ('exclusions_version', models.CharField(default='v1.0', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('expected_loss_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('zone_risk_multiplier', models.FloatField(blank=True, null=True)),
                ('premium_breakdown', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-week_start'],
            },
        ),
    ]
