# Generated by Django 5.2.12 on 2026-04-03 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('policies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exclusionacknowledgment',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusion_acks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weeklypolicy',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_policies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exclusionacknowledgment',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgments', to='policies.weeklypolicy'),
        ),
        migrations.AddIndex(
            model_name='weeklypolicy',
            index=models.Index(fields=['worker', 'status', 'week_start', 'week_end'], name='policies_we_worker__c8bce8_idx'),
        ),
    ]
