# Generated by Django 5.2.13 on 2026-04-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0003_weeklypolicy_active_week_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklypolicy',
            name='covered_triggers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
