# Generated by Django 6.0.3 on 2026-03-16 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('claims', '0001_initial'),
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payout_channel', models.CharField(default='UPI', max_length=30)),
                ('payout_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('transaction_ref', models.CharField(blank=True, default='', max_length=120)),
                ('payout_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payout', to='claims.claim')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='workers.workerprofile')),
            ],
        ),
    ]
