# Generated by Django 6.0.3 on 2026-03-16 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gps_match_score', models.FloatField(default=1.0)),
                ('duplicate_flag', models.BooleanField(default=False)),
                ('activity_match_score', models.FloatField(default=1.0)),
                ('anomaly_score', models.FloatField(default=0.0)),
                ('decision', models.CharField(choices=[('approve', 'Approve'), ('review', 'Review'), ('reject', 'Reject')], default='approve', max_length=10)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_check', to='claims.claim')),
            ],
        ),
    ]
