# Generated by Django 6.0.3 on 2026-03-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fraudcheck',
            name='fraud_score',
            field=models.IntegerField(default=0),
        ),
    ]
