# Generated by Django 6.0.3 on 2026-03-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud', '0002_fraudcheck_fraud_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='fraudcheck',
            name='fraud_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fraudcheck',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
